name: Run API Test

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'
    - cron: '30 13 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
          newman run "Inwarranty-flow Collection Latest.postman_collection.json" \
          -e "./QA Environment.postman_environment.json" \
          -r htmlextra \
          --verbose || echo "Newman run failed"

      - name: Upload Newman HTML Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: newman-report
          path: newman/report.html
